export const transportConfig = [
  (`('car', 'Car', 'Машина', 
  'https://res.cloudinary.com/dum5vvgxg/image/upload/v1626206302/transport/car_h6l2fy.jpg', 
  'https://res.cloudinary.com/dum5vvgxg/video/upload/v1626206302/transport/car_mfexjh.mp3', 'transport')`),
  (`('bus', 'Bus', 'Автобус', 
  'https://res.cloudinary.com/dum5vvgxg/image/upload/v1626206303/transport/bus_myi6on.jpg', 
  'https://res.cloudinary.com/dum5vvgxg/video/upload/v1626206302/transport/bus_e8gqxc.mp3', 'transport')`),
  (`('bicycle', 'Bicycle', 'Велосипед', 
  'https://res.cloudinary.com/dum5vvgxg/image/upload/v1626206302/transport/bicycle_xwivmc.jpg', 
  'https://res.cloudinary.com/dum5vvgxg/video/upload/v1626206302/transport/bicycle_uffjls.mp3', 'transport')`),
  (`('train', 'Train', 'Поезд', 
  'https://res.cloudinary.com/dum5vvgxg/image/upload/v1626206301/transport/train_lwvui5.jpg', 
  'https://res.cloudinary.com/dum5vvgxg/video/upload/v1626206301/transport/train_w66pxv.mp3', 'transport')`),
  (`('plane', 'Plane', 'Самолет', 
  'https://res.cloudinary.com/dum5vvgxg/image/upload/v1626206301/transport/plane_dq8iqf.jpg', 
  'https://res.cloudinary.com/dum5vvgxg/video/upload/v1626206301/transport/plane_l43fsz.mp3', 'transport')`),
  (`('helicopter', 'Helicopter', 'Вертолет', 
  'https://res.cloudinary.com/dum5vvgxg/image/upload/v1626206302/transport/helicopter_psrkfi.jpg', 
  'https://res.cloudinary.com/dum5vvgxg/video/upload/v1626206302/transport/helicopter_es7bew.mp3', 'transport')`),
  (`('ship', 'Ship', 'Корабль', 
  'https://res.cloudinary.com/dum5vvgxg/image/upload/v1626206301/transport/ship_wpjjpt.jpg', 
  'https://res.cloudinary.com/dum5vvgxg/video/upload/v1626206301/transport/ship_fhvd0o.mp3', 'transport')`),
  (`('motorcycle', 'Motorcycle', 'Мотоцикл', 
  'https://res.cloudinary.com/dum5vvgxg/image/upload/v1626206302/transport/motorcycle_yzroil.jpg', 
  'https://res.cloudinary.com/dum5vvgxg/video/upload/v1626206302/transport/motorcycle_sq9vvk.mp3', 'transport')`)
];