export const TOGGLE_GAME_MODE = 'TOGGLE_GAME_MODE';
export const IS_GAME_STARTED = 'IS_GAME_STARTED';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const MISTAKES_COUNT = 'MISTAKES_COUNT';
export const SET_WORDS_IN_PLAY = 'SET_WORDS_IN_PLAY';
export const SET_CURRENT_WORD = 'SET_CURRENT_WORD';
