export const TOGGLE_GAME_MODE = 'TOGGLE_GAME_MODE';
export const START_GAME = 'START_GAME';
export const STOP_GAME = 'STOP_GAME';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const NEXT_CURRENT_WORD = 'NEXT_CURRENT_WORD';
export const MISTAKES_COUNT = 'MISTAKES_COUNT';